### ISSUE TITLE
Retrieving all clients always fails with a 401

### ISSUE THREAD

**Issue by maeve** [G5/g5_foundation_client#13]
#12 removed the auth token from the request constructed by `G5FoundationClient:Fetcher.fetch_url` for all endpoints. While the auth token is not necessary to retrieve a particular client by uid from the g5-hub, it *is* necessary for other protected endpoints, such as the clients index.

As it stands right now, `G5FoundationClient::Client.all_client_uids` always fails with a 401 because there is no access token on the request. This means that in [g5_updatable](https://github.com/G5/g5_updatable), the `rake g5_updatable:load_all` task which depends on this method always fails as well.

**Comment by jcstringer** [comment]
@maeve good catch. I don't see any reason why we can't leave the auth token in the header, I just removed it because it seemed unnecessary but I clearly missed this use case. If you're +1 I'll just revert that change.

**Comment by maeve** [comment]
:+1: Sounds good to me.

**Comment by jcstringer** [comment]
I've now fixed this in https://github.com/G5/g5_foundation_client/pull/14
